# require 'byebug'
require 'json'
require 'typhoeus'
require 'oauth'
require 'oauth/request_proxy/typhoeus_request'

$LOAD_PATH << './lib'
require 'authorizer'

def create_tweet(url, oauth_params, tweet_params)
	options = {
	    :method => :post,
	    headers: {
        "User-Agent": "v1.1VUpdateStatusRuby",
        "content-type": "application/json"
	    },
			params: tweet_params
	}
  request = Typhoeus::Request.new(url, options)
	oauth_helper = OAuth::Client::Helper.new(request, oauth_params.merge(:request_uri => url))
	request.options[:headers].merge!({"Authorization" => oauth_helper.header}) # Signs the request
	response = request.run

	return response
end

create_tweet_url = "https://api.twitter.com/1.1/statuses/update.json"

# these are generated by your twitter api app
consumer_key = ENV['CONSUMER_KEY']
consumer_secret = ENV['CONSUMER_SECRET']
# these are generated from 3-step oauth after twitter acct has granted
# permissions
token_key = ENV['ACCESS_TOKEN']
token_secret = ENV['ACCESS_TOKEN_SECRET']

# puts "Enter tweet text: "
# tweet_text = gets.strip
tweet_text = "Holy shit I did it I just tweeted this shit from the command-line using Ruby in Linux I am a god or at least someone who has the skills of an engineer from 8 years ago"
tweet_params = { status: tweet_text }

authorizer = Authorizer.new
oauth_params = { consumer: authorizer.oauth_consumer, token: authorizer.oauth_token }
  
response = create_tweet(create_tweet_url, oauth_params, tweet_params)
puts response.code, JSON.pretty_generate(JSON.parse(response.body))
